### ISSUE TITLE
function missing

### ISSUE THREAD

**Issue by H4bu** [t0x0-nz/electrode#1]
I just get this error:
```
  File "/root/tools/electrode/common/security.py", line 84, in prepareScan
    if element_exists(driver, authConfig.usernameText):
NameError: global name 'element_exists' is not defined

```
No such function exists in Selenium, unless I am mistaken.  Is there a function missing from the electrode repo?

**Comment by t0x0-nz** [comment]
Thanks for reporting this @H4bu. Looks like I dropped prepareScan in the wrong module when restructuring electrode... and there was no import of elementExists in 'security'. Fixed in v1.1.1.
